### ISSUE TITLE
Hardware HDC1080 HDC2080 SI7021 HTU21D

### ISSUE THREAD

**Issue by HeinKlocktein** [liutyi/arduino-humidity-sensors-test#3]
Dear Oleksandr,

This is not an issue, but an attempt to clarify.
But first let me thank you for your great work!
The sensor overview helps me a lot :-)

On the hardware site https://wiki.liutyi.info/display/ARDUINO/HDC1080 you write:
"same i2c address as SHT2x, HTU21d, Si7021, but not compatible by protocol, voltage range 2.7-5.5v"

I am using a Raspberry Pi and at first I accidentally addressed the other sensors with a module for the HDC1080 (HDC1008). The address is the same.

At least the 4 (HDC1080, HDC2080, SI7021, HTU21D) are all read cleanly. 
SHT2x does not work (as aspected) but HTU21d and Si7021 working with the modul of the HDC1008 without any changes.

Best regards from germany,

Hein

**Comment by liutyi** [comment]
Hmm.. interesting, I think I did some testing before left that note in article, but OK. it seems it maybe compatible by protocols, so I have that note removed.
![HTU21D_SHT2x_compatibility](https://user-images.githubusercontent.com/11354088/114454099-e31a5500-9be2-11eb-8f25-b1316f6a2fc1.JPG)
![HDC1080_SHT2x_compatibility](https://user-images.githubusercontent.com/11354088/114454103-e44b8200-9be2-11eb-827b-66815322cd9a.JPG)
